/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_curso.gui;

import com.mycompany.gestion_curso.model.Docente;
import com.mycompany.gestion_curso.servicios.ServicioDocente;

/**
 *
 * @author user
 */
public class GUIEliminarDocente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEliminarDocente.class.getName());

    /**
     * Creates new form GUIEliminarDocente
     */
    public GUIEliminarDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalirDocente = new javax.swing.JButton();
        btnLimpiarDocente = new javax.swing.JButton();
        txtEstadoDocete = new javax.swing.JTextField();
        lblEstadoDocente = new javax.swing.JLabel();
        jLabel1CodigoDocente = new javax.swing.JLabel();
        txtCodigoDelDocente = new javax.swing.JTextField();
        txtSalarioDocente = new javax.swing.JTextField();
        lblSalarioActualDocente = new javax.swing.JLabel();
        txtDisponibilidadDocente = new javax.swing.JTextField();
        lblDisponibilidadDocente = new javax.swing.JLabel();
        txtNombreActualDocente = new javax.swing.JTextField();
        lblNombreActualDocente = new javax.swing.JLabel();
        lblCodigoDocente = new javax.swing.JLabel();
        txtCodigoDocente = new javax.swing.JTextField();
        btnBuscarDocente = new javax.swing.JButton();
        btnEliminarDocente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalirDocente.setText("Salir");
        btnSalirDocente.addActionListener(this::btnSalirDocenteActionPerformed);

        btnLimpiarDocente.setText("Limpiar");
        btnLimpiarDocente.addActionListener(this::btnLimpiarDocenteActionPerformed);

        txtEstadoDocete.setEditable(false);

        lblEstadoDocente.setText("Estado: ");

        jLabel1CodigoDocente.setText("Codigo Del Docente");

        txtCodigoDelDocente.setEditable(false);
        txtCodigoDelDocente.addActionListener(this::txtCodigoDelDocenteActionPerformed);

        txtSalarioDocente.setEditable(false);

        lblSalarioActualDocente.setText("Salario");

        txtDisponibilidadDocente.setEditable(false);

        lblDisponibilidadDocente.setText("Disponibilidad:");

        txtNombreActualDocente.setEditable(false);

        lblNombreActualDocente.setText("Nombre actual: ");

        lblCodigoDocente.setText("Código: ");

        txtCodigoDocente.addActionListener(this::txtCodigoDocenteActionPerformed);

        btnBuscarDocente.setText("Buscar");
        btnBuscarDocente.addActionListener(this::btnBuscarDocenteActionPerformed);

        btnEliminarDocente.setForeground(new java.awt.Color(255, 51, 51));
        btnEliminarDocente.setText("Eliminar");
        btnEliminarDocente.setEnabled(false);
        btnEliminarDocente.addActionListener(this::btnEliminarDocenteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstadoDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEstadoDocete, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSalarioActualDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSalarioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtNombreActualDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1CodigoDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(txtCodigoDelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDisponibilidadDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDisponibilidadDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnLimpiarDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarDocente)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnEliminarDocente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCodigoDocente)
                            .addGap(60, 60, 60)
                            .addComponent(txtCodigoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblNombreActualDocente))
                    .addContainerGap(154, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnBuscarDocente)
                .addGap(18, 18, 18)
                .addComponent(txtNombreActualDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisponibilidadDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisponibilidadDocente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioActualDocente)
                    .addComponent(txtSalarioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoDelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1CodigoDocente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoDocente)
                    .addComponent(txtEstadoDocete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnEliminarDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarDocente)
                    .addComponent(btnSalirDocente))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoDocente)
                        .addComponent(txtCodigoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(lblNombreActualDocente)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDocenteActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirDocenteActionPerformed

    private void btnLimpiarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDocenteActionPerformed
        // TODO add your handling code here:

        txtCodigoDocente.setText("");

        txtNombreActualDocente.setText("");
        txtDisponibilidadDocente.setText("");
        
        txtSalarioDocente.setText("");
        txtEstadoDocete.setText("");

        btnEliminarDocente.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarDocenteActionPerformed

    private void txtCodigoDelDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDelDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDelDocenteActionPerformed

    private void txtCodigoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDocenteActionPerformed

    private void btnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocenteActionPerformed
       
        int codigo;

        try {
            codigo = Integer.parseInt(txtCodigoDocente.getText().trim());

            Docente docente = ServicioDocente.buscarDocentePorCodigo(codigo);

            if (docente != null) {

                txtNombreActualDocente.setText(docente.getNombre());

                if (docente.isPlanta()) {
                    txtDisponibilidadDocente.setText("De Planta");
                } else {
                    txtDisponibilidadDocente.setText("No de Planta");
                }

                txtSalarioDocente.setText(String.valueOf(docente.getSalario()));

                txtEstadoDocete.setText(docente.getEstado().toUpperCase());
                
                // Si el docente ya está INACTIVO, el botón de eliminar no debería prenderse
                if (docente.getEstado().equalsIgnoreCase("INACTIVO")) {
                    btnEliminarDocente.setEnabled(false);
                    javax.swing.JOptionPane.showMessageDialog(this, "Este docente ya se encuentra eliminado (INACTIVO).");
                } else {
                    btnEliminarDocente.setEnabled(true);
                }
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Docente no encontrado!");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnBuscarDocenteActionPerformed

    private void btnEliminarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDocenteActionPerformed
        

        int codigo;

        try {
            codigo = Integer.parseInt(txtCodigoDocente.getText().trim());
            
            // Llamamos al servicio de Docente
            ServicioDocente.eliminarDocentePorCodigo(codigo);
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Docente eliminado correctamente!");
            
            // Replicando la lógica de Curso: mostramos INACTIVO y apagamos el botón
            txtEstadoDocete.setText("INACTIVO");
            btnEliminarDocente.setEnabled(false);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnEliminarDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEliminarDocente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDocente;
    private javax.swing.JButton btnEliminarDocente;
    private javax.swing.JButton btnLimpiarDocente;
    private javax.swing.JButton btnSalirDocente;
    private javax.swing.JLabel jLabel1CodigoDocente;
    private javax.swing.JLabel lblCodigoDocente;
    private javax.swing.JLabel lblDisponibilidadDocente;
    private javax.swing.JLabel lblEstadoDocente;
    private javax.swing.JLabel lblNombreActualDocente;
    private javax.swing.JLabel lblSalarioActualDocente;
    private javax.swing.JTextField txtCodigoDelDocente;
    private javax.swing.JTextField txtCodigoDocente;
    private javax.swing.JTextField txtDisponibilidadDocente;
    private javax.swing.JTextField txtEstadoDocete;
    private javax.swing.JTextField txtNombreActualDocente;
    private javax.swing.JTextField txtSalarioDocente;
    // End of variables declaration//GEN-END:variables
}
